
const actionTypes = Object.freeze({
    ADD_TAB: 'ADD_TAB',
    REMOVE_TAB: 'REMOVE_TAB',
    SWITCH_SPRITE_TAB: 'SWITCH_SPRITE_TAB',
    ADD_SPRITE_CMD: 'ADD_SPRITE_CMD',
    REMOVE_SPRITE_CMD: 'REMOVE_SPRITE_CMD',
    UPDATE_HISTORY_CMD:'UPDATE_HISTORY_CMD'
});

export default actionTypes;
